language: node_js
node_js:
  - "5.1"
cache:
  directories:
    - node_modules
addons:
  code_climate:
    repo_token: afda4d694c2dccd00e31f727255546cad8c7de98ee2d379019080f23f0490688
before_install: npm install -g codeclimate-test-reporter
after_success: npm run cover && ./node_modules/.bin/nyc report --reporter=text-lcov | codeclimate-test-reporter